[package]
name = "day22_part2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.4"
modinverse = "0.1.1"
num-bigint = "0.4.4"
